export const AudioProcessingConstants = {
  GAIN_SMOOTHING_NORMAL: 0.1,
  GAIN_SMOOTHING_SEEK_RESET: 0.05,
  PEAK_TO_RMS_THRESHOLD: 1.5,
  PEAK_VOLUME_MULTIPLIER: 0.7,
  NORMALIZATION_INTERVAL_MS: 50,
} as const;
